language: python
    python:
      - "3.7"
    install:
      - pip install -r requirements.txt
      - pip install pytest coverage codecov
    before_script:
      - mysql -e 'create database test;' -u root
    script:
      - coverage run --source='.' manage.py test
      - coverage run --source='.' pytest
    after_success:
      - codecov